---
ungrouped:
  hosts:

APAC:
  hosts:
    gurgaoncorp11-vgw.gw.sg.XXXX.com:
      model: C3925/K9
      serial: YYYY
      ip: 192.251.0.35
    singaporedc43-pfr.gw.sg.XXXX.com:
      model: ISR4331/K9
      serial: YYYY
      ip: 192.254.0.28
    shanghai24-bro.gw.sg.XXXX.com:
      model: ISR4331/K9
      serial: YYYY
      ip: 192.202.130.141
    batangas1-xnr.gw.sg.XXXX.com:
      model: ISR4331/K9
      serial: YYYY
      ip: 192.246.0.25
    shanghaidc429-ext-pfr.gw.sg.XXXX.com:
      model: ISR4321/K9
      serial: YYYY
      ip: 192.252.0.104
